# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.server_logs_response import ServerLogsResponse
from ..types.server_status import ServerStatus
from ..types.shutdown_server_response import ShutdownServerResponse
from .raw_client import AsyncRawServerClient, RawServerClient
from .types.logs_server_request_level import LogsServerRequestLevel


class ServerClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawServerClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawServerClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawServerClient
        """
        return self._raw_client

    def status(self, *, request_options: typing.Optional[RequestOptions] = None) -> ServerStatus:
        """
        Returns server health, uptime, version info, and connected camera count.
        Used by the TypeScript `ServerManager` to confirm the server is ready after spawning the binary.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ServerStatus
            Server is running

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.server.status()
        """
        _response = self._raw_client.status(request_options=request_options)
        return _response.data

    def logs(
        self,
        *,
        lines: typing.Optional[int] = None,
        level: typing.Optional[LogsServerRequestLevel] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ServerLogsResponse:
        """
        Returns buffered server log output. Useful for debugging connection issues,
        SDK errors, and property change confirmations without accessing the terminal.

        Parameters
        ----------
        lines : typing.Optional[int]
            Number of recent log lines to return (default 100)

        level : typing.Optional[LogsServerRequestLevel]
            Minimum log level filter

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ServerLogsResponse
            Log entries

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.server.logs()
        """
        _response = self._raw_client.logs(lines=lines, level=level, request_options=request_options)
        return _response.data

    def shutdown(self, *, request_options: typing.Optional[RequestOptions] = None) -> ShutdownServerResponse:
        """
        Initiates graceful shutdown: disconnects all cameras, closes SSE
        connections, then exits.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ShutdownServerResponse
            Shutdown initiated

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.server.shutdown()
        """
        _response = self._raw_client.shutdown(request_options=request_options)
        return _response.data


class AsyncServerClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawServerClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawServerClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawServerClient
        """
        return self._raw_client

    async def status(self, *, request_options: typing.Optional[RequestOptions] = None) -> ServerStatus:
        """
        Returns server health, uptime, version info, and connected camera count.
        Used by the TypeScript `ServerManager` to confirm the server is ready after spawning the binary.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ServerStatus
            Server is running

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.server.status()


        asyncio.run(main())
        """
        _response = await self._raw_client.status(request_options=request_options)
        return _response.data

    async def logs(
        self,
        *,
        lines: typing.Optional[int] = None,
        level: typing.Optional[LogsServerRequestLevel] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ServerLogsResponse:
        """
        Returns buffered server log output. Useful for debugging connection issues,
        SDK errors, and property change confirmations without accessing the terminal.

        Parameters
        ----------
        lines : typing.Optional[int]
            Number of recent log lines to return (default 100)

        level : typing.Optional[LogsServerRequestLevel]
            Minimum log level filter

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ServerLogsResponse
            Log entries

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.server.logs()


        asyncio.run(main())
        """
        _response = await self._raw_client.logs(lines=lines, level=level, request_options=request_options)
        return _response.data

    async def shutdown(self, *, request_options: typing.Optional[RequestOptions] = None) -> ShutdownServerResponse:
        """
        Initiates graceful shutdown: disconnects all cameras, closes SSE
        connections, then exits.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ShutdownServerResponse
            Shutdown initiated

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.server.shutdown()


        asyncio.run(main())
        """
        _response = await self._raw_client.shutdown(request_options=request_options)
        return _response.data
