# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.camera_list_response import CameraListResponse
from ..types.camera_response import CameraResponse
from ..types.connection_mode import ConnectionMode
from ..types.connection_status_response import ConnectionStatusResponse
from .raw_client import AsyncRawCamerasClient, RawCamerasClient
from .types.connection_request_reconnecting import ConnectionRequestReconnecting

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CamerasClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCamerasClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCamerasClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCamerasClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> CameraListResponse:
        """
        Enumerate all cameras connected via USB and network.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraListResponse
            Camera list retrieved

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.cameras.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def get_connection_status(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ConnectionStatusResponse:
        """
        Returns the current connection state for a camera (connected/disconnected,
        model, id). When connected, `data.mode` reports the active SDK
        connection mode (`remote` / `remote-transfer` / `contents`).

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConnectionStatusResponse
            Connection status

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.cameras.get_connection_status(
            camera_id="cameraId",
        )
        """
        _response = self._raw_client.get_connection_status(camera_id, request_options=request_options)
        return _response.data

    def connect(
        self,
        camera_id: str,
        *,
        mode: typing.Optional[ConnectionMode] = OMIT,
        username: typing.Optional[str] = OMIT,
        password: typing.Optional[str] = OMIT,
        reconnecting: typing.Optional[ConnectionRequestReconnecting] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CameraResponse:
        """
        Establish connection in the specified mode. Defaults to `remote` if no mode provided.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        mode : typing.Optional[ConnectionMode]

        username : typing.Optional[str]
            For network cameras

        password : typing.Optional[str]
            For network cameras

        reconnecting : typing.Optional[ConnectionRequestReconnecting]
            Auto-reconnect on disconnection

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Camera connected

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.cameras.connect(
            camera_id="cameraId",
        )
        """
        _response = self._raw_client.connect(
            camera_id,
            mode=mode,
            username=username,
            password=password,
            reconnecting=reconnecting,
            request_options=request_options,
        )
        return _response.data

    def disconnect(self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> CameraResponse:
        """
        Cleanly disconnects from the specified camera. Server emits a synthetic
        `disconnected` SSE event before clearing internal callbacks.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Camera disconnected

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.cameras.disconnect(
            camera_id="cameraId",
        )
        """
        _response = self._raw_client.disconnect(camera_id, request_options=request_options)
        return _response.data


class AsyncCamerasClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCamerasClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCamerasClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCamerasClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> CameraListResponse:
        """
        Enumerate all cameras connected via USB and network.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraListResponse
            Camera list retrieved

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.cameras.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def get_connection_status(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ConnectionStatusResponse:
        """
        Returns the current connection state for a camera (connected/disconnected,
        model, id). When connected, `data.mode` reports the active SDK
        connection mode (`remote` / `remote-transfer` / `contents`).

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConnectionStatusResponse
            Connection status

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.cameras.get_connection_status(
                camera_id="cameraId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_connection_status(camera_id, request_options=request_options)
        return _response.data

    async def connect(
        self,
        camera_id: str,
        *,
        mode: typing.Optional[ConnectionMode] = OMIT,
        username: typing.Optional[str] = OMIT,
        password: typing.Optional[str] = OMIT,
        reconnecting: typing.Optional[ConnectionRequestReconnecting] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CameraResponse:
        """
        Establish connection in the specified mode. Defaults to `remote` if no mode provided.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        mode : typing.Optional[ConnectionMode]

        username : typing.Optional[str]
            For network cameras

        password : typing.Optional[str]
            For network cameras

        reconnecting : typing.Optional[ConnectionRequestReconnecting]
            Auto-reconnect on disconnection

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Camera connected

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.cameras.connect(
                camera_id="cameraId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.connect(
            camera_id,
            mode=mode,
            username=username,
            password=password,
            reconnecting=reconnecting,
            request_options=request_options,
        )
        return _response.data

    async def disconnect(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CameraResponse:
        """
        Cleanly disconnects from the specified camera. Server emits a synthetic
        `disconnected` SSE event before clearing internal callbacks.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Camera disconnected

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.cameras.disconnect(
                camera_id="cameraId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.disconnect(camera_id, request_options=request_options)
        return _response.data
