# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.camera_response import CameraResponse
from ..types.zoom_request import ZoomRequest
from .raw_client import AsyncRawActionsClient, RawActionsClient
from .types.shutter_request_action import ShutterRequestAction

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ActionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawActionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawActionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawActionsClient
        """
        return self._raw_client

    def shutter(
        self,
        camera_id: str,
        *,
        action: typing.Optional[ShutterRequestAction] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CameraResponse:
        """
        Single shot (no body or empty body), or continuous shooting with `down`/`up` control.
        For continuous shooting, set drive mode to a continuous mode first.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        action : typing.Optional[ShutterRequestAction]
            For continuous shooting: `down` to start, `up` to stop.
            Omit for single shot.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Shutter action executed

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.actions.shutter(
            camera_id="cameraId",
        )
        """
        _response = self._raw_client.shutter(camera_id, action=action, request_options=request_options)
        return _response.data

    def half_press(self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> CameraResponse:
        """
        Half-press the shutter button to lock autofocus. No body required.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Half-press executed

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.actions.half_press(
            camera_id="cameraId",
        )
        """
        _response = self._raw_client.half_press(camera_id, request_options=request_options)
        return _response.data

    def af_shutter(self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> CameraResponse:
        """
        Autofocus then immediately capture in one operation. No body required.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            AF + shutter executed

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.actions.af_shutter(
            camera_id="cameraId",
        )
        """
        _response = self._raw_client.af_shutter(camera_id, request_options=request_options)
        return _response.data

    def zoom(
        self, camera_id: str, *, request: ZoomRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> CameraResponse:
        """
        Control power zoom lenses. Requires a power zoom lens to be attached.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request : ZoomRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Zoom command executed

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient, ZoomDirectionalRequest

        client = AlphaSDKClient()
        client.actions.zoom(
            camera_id="cameraId",
            request=ZoomDirectionalRequest(
                direction="in",
                speed="normal",
            ),
        )
        """
        _response = self._raw_client.zoom(camera_id, request=request, request_options=request_options)
        return _response.data

    def movie_rec(self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> CameraResponse:
        """
        Start or stop movie recording. Server tracks the current state via the SDK
        and toggles it on each call. Camera must be in a movie shooting mode.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Movie recording toggled

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.actions.movie_rec(
            camera_id="cameraId",
        )
        """
        _response = self._raw_client.movie_rec(camera_id, request_options=request_options)
        return _response.data

    def focus_near_far(
        self, camera_id: str, *, step: int, request_options: typing.Optional[RequestOptions] = None
    ) -> CameraResponse:
        """
        Move focus toward near or far in discrete steps.
        Range: `-7` (near, max speed) to `+7` (far, max speed).
        Magnitude controls speed. `0` is not valid.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        step : int
            Negative = near, positive = far. Magnitude controls speed. 0 is invalid.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Focus command executed

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.actions.focus_near_far(
            camera_id="cameraId",
            step=1,
        )
        """
        _response = self._raw_client.focus_near_far(camera_id, step=step, request_options=request_options)
        return _response.data


class AsyncActionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawActionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawActionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawActionsClient
        """
        return self._raw_client

    async def shutter(
        self,
        camera_id: str,
        *,
        action: typing.Optional[ShutterRequestAction] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CameraResponse:
        """
        Single shot (no body or empty body), or continuous shooting with `down`/`up` control.
        For continuous shooting, set drive mode to a continuous mode first.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        action : typing.Optional[ShutterRequestAction]
            For continuous shooting: `down` to start, `up` to stop.
            Omit for single shot.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Shutter action executed

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.actions.shutter(
                camera_id="cameraId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.shutter(camera_id, action=action, request_options=request_options)
        return _response.data

    async def half_press(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CameraResponse:
        """
        Half-press the shutter button to lock autofocus. No body required.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Half-press executed

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.actions.half_press(
                camera_id="cameraId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.half_press(camera_id, request_options=request_options)
        return _response.data

    async def af_shutter(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CameraResponse:
        """
        Autofocus then immediately capture in one operation. No body required.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            AF + shutter executed

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.actions.af_shutter(
                camera_id="cameraId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.af_shutter(camera_id, request_options=request_options)
        return _response.data

    async def zoom(
        self, camera_id: str, *, request: ZoomRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> CameraResponse:
        """
        Control power zoom lenses. Requires a power zoom lens to be attached.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request : ZoomRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Zoom command executed

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient, ZoomDirectionalRequest

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.actions.zoom(
                camera_id="cameraId",
                request=ZoomDirectionalRequest(
                    direction="in",
                    speed="normal",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.zoom(camera_id, request=request, request_options=request_options)
        return _response.data

    async def movie_rec(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CameraResponse:
        """
        Start or stop movie recording. Server tracks the current state via the SDK
        and toggles it on each call. Camera must be in a movie shooting mode.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Movie recording toggled

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.actions.movie_rec(
                camera_id="cameraId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.movie_rec(camera_id, request_options=request_options)
        return _response.data

    async def focus_near_far(
        self, camera_id: str, *, step: int, request_options: typing.Optional[RequestOptions] = None
    ) -> CameraResponse:
        """
        Move focus toward near or far in discrete steps.
        Range: `-7` (near, max speed) to `+7` (far, max speed).
        Magnitude controls speed. `0` is not valid.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        step : int
            Negative = near, positive = far. Magnitude controls speed. 0 is invalid.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Focus command executed

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.actions.focus_near_far(
                camera_id="cameraId",
                step=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.focus_near_far(camera_id, step=step, request_options=request_options)
        return _response.data
