# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..types.camera_response import CameraResponse
from ..types.error_response import ErrorResponse
from ..types.zoom_request import ZoomRequest
from .types.shutter_request_action import ShutterRequestAction
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawActionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def shutter(
        self,
        camera_id: str,
        *,
        action: typing.Optional[ShutterRequestAction] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CameraResponse]:
        """
        Single shot (no body or empty body), or continuous shooting with `down`/`up` control.
        For continuous shooting, set drive mode to a continuous mode first.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        action : typing.Optional[ShutterRequestAction]
            For continuous shooting: `down` to start, `up` to stop.
            Omit for single shot.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CameraResponse]
            Shutter action executed
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/actions/shutter",
            method="POST",
            json={
                "action": action,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CameraResponse,
                    parse_obj_as(
                        type_=CameraResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def half_press(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[CameraResponse]:
        """
        Half-press the shutter button to lock autofocus. No body required.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CameraResponse]
            Half-press executed
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/actions/half-press",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CameraResponse,
                    parse_obj_as(
                        type_=CameraResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def af_shutter(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[CameraResponse]:
        """
        Autofocus then immediately capture in one operation. No body required.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CameraResponse]
            AF + shutter executed
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/actions/af-shutter",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CameraResponse,
                    parse_obj_as(
                        type_=CameraResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def zoom(
        self, camera_id: str, *, request: ZoomRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[CameraResponse]:
        """
        Control power zoom lenses. Requires a power zoom lens to be attached.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request : ZoomRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CameraResponse]
            Zoom command executed
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/actions/zoom",
            method="POST",
            json=convert_and_respect_annotation_metadata(object_=request, annotation=ZoomRequest, direction="write"),
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CameraResponse,
                    parse_obj_as(
                        type_=CameraResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def movie_rec(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[CameraResponse]:
        """
        Start or stop movie recording. Server tracks the current state via the SDK
        and toggles it on each call. Camera must be in a movie shooting mode.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CameraResponse]
            Movie recording toggled
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/actions/movie-rec",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CameraResponse,
                    parse_obj_as(
                        type_=CameraResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def focus_near_far(
        self, camera_id: str, *, step: int, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[CameraResponse]:
        """
        Move focus toward near or far in discrete steps.
        Range: `-7` (near, max speed) to `+7` (far, max speed).
        Magnitude controls speed. `0` is not valid.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        step : int
            Negative = near, positive = far. Magnitude controls speed. 0 is invalid.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CameraResponse]
            Focus command executed
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/actions/focus-near-far",
            method="POST",
            json={
                "step": step,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CameraResponse,
                    parse_obj_as(
                        type_=CameraResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawActionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def shutter(
        self,
        camera_id: str,
        *,
        action: typing.Optional[ShutterRequestAction] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CameraResponse]:
        """
        Single shot (no body or empty body), or continuous shooting with `down`/`up` control.
        For continuous shooting, set drive mode to a continuous mode first.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        action : typing.Optional[ShutterRequestAction]
            For continuous shooting: `down` to start, `up` to stop.
            Omit for single shot.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CameraResponse]
            Shutter action executed
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/actions/shutter",
            method="POST",
            json={
                "action": action,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CameraResponse,
                    parse_obj_as(
                        type_=CameraResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def half_press(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[CameraResponse]:
        """
        Half-press the shutter button to lock autofocus. No body required.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CameraResponse]
            Half-press executed
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/actions/half-press",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CameraResponse,
                    parse_obj_as(
                        type_=CameraResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def af_shutter(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[CameraResponse]:
        """
        Autofocus then immediately capture in one operation. No body required.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CameraResponse]
            AF + shutter executed
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/actions/af-shutter",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CameraResponse,
                    parse_obj_as(
                        type_=CameraResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def zoom(
        self, camera_id: str, *, request: ZoomRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[CameraResponse]:
        """
        Control power zoom lenses. Requires a power zoom lens to be attached.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request : ZoomRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CameraResponse]
            Zoom command executed
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/actions/zoom",
            method="POST",
            json=convert_and_respect_annotation_metadata(object_=request, annotation=ZoomRequest, direction="write"),
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CameraResponse,
                    parse_obj_as(
                        type_=CameraResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def movie_rec(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[CameraResponse]:
        """
        Start or stop movie recording. Server tracks the current state via the SDK
        and toggles it on each call. Camera must be in a movie shooting mode.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CameraResponse]
            Movie recording toggled
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/actions/movie-rec",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CameraResponse,
                    parse_obj_as(
                        type_=CameraResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def focus_near_far(
        self, camera_id: str, *, step: int, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[CameraResponse]:
        """
        Move focus toward near or far in discrete steps.
        Range: `-7` (near, max speed) to `+7` (far, max speed).
        Magnitude controls speed. `0` is not valid.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        step : int
            Negative = near, positive = far. Magnitude controls speed. 0 is invalid.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CameraResponse]
            Focus command executed
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/actions/focus-near-far",
            method="POST",
            json={
                "step": step,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CameraResponse,
                    parse_obj_as(
                        type_=CameraResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
