# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.async_operation_response import AsyncOperationResponse
from ..types.compressed_download_response import CompressedDownloadResponse
from ..types.sd_card_file_list_response import SdCardFileListResponse
from .raw_client import AsyncRawSdCardClient, RawSdCardClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SdCardClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSdCardClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSdCardClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSdCardClient
        """
        return self._raw_client

    def list(
        self, camera_id: str, slot_number: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SdCardFileListResponse:
        """
        List files on the SD card. Requires `remote-transfer` or `contents` mode.
        Returns 400 if called in `remote` mode.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        slot_number : int
            SD card slot number (1 or 2)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SdCardFileListResponse
            File list retrieved

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.sd_card.list(
            camera_id="cameraId",
            slot_number=1,
        )
        """
        _response = self._raw_client.list(camera_id, slot_number, request_options=request_options)
        return _response.data

    def download(
        self,
        camera_id: str,
        slot_number: int,
        content_id: int,
        file_id: int,
        *,
        save_path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncOperationResponse:
        """
        Initiates an async download of a specific file from the SD card to the host PC.
        Returns immediately; completion is signaled via the `downloadComplete` SSE event
        (remote/remote-transfer modes) or via filesystem polling (contents-transfer mode).

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        slot_number : int
            SD card slot number (1 or 2)

        content_id : int
            SDK content identifier from `listSDCardFiles` response

        file_id : int
            SDK file identifier from `listSDCardFiles` response (always `0` in contents-transfer mode)

        save_path : typing.Optional[str]
            Directory path on host PC to save the file

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncOperationResponse
            Download accepted (async)

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.sd_card.download(
            camera_id="cameraId",
            slot_number=1,
            content_id=1,
            file_id=1,
        )
        """
        _response = self._raw_client.download(
            camera_id, slot_number, content_id, file_id, save_path=save_path, request_options=request_options
        )
        return _response.data

    def download_thumbnail(
        self,
        camera_id: str,
        slot_number: int,
        content_id: int,
        file_id: int,
        *,
        save_path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CompressedDownloadResponse:
        """
        Initiates an async download of the file's thumbnail (small JPEG preview).
        Used for fast file browser previews. Remote-transfer mode only.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        slot_number : int
            SD card slot number (1 or 2)

        content_id : int
            SDK content identifier from `listSDCardFiles` response

        file_id : int
            SDK file identifier from `listSDCardFiles` response (always `0` in contents-transfer mode)

        save_path : typing.Optional[str]
            Directory path on host PC to save the file

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CompressedDownloadResponse
            Thumbnail download accepted (async)

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.sd_card.download_thumbnail(
            camera_id="cameraId",
            slot_number=1,
            content_id=1,
            file_id=1,
        )
        """
        _response = self._raw_client.download_thumbnail(
            camera_id, slot_number, content_id, file_id, save_path=save_path, request_options=request_options
        )
        return _response.data

    def download_screennail(
        self,
        camera_id: str,
        slot_number: int,
        content_id: int,
        file_id: int,
        *,
        save_path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CompressedDownloadResponse:
        """
        Initiates an async download of the file's screennail (medium JPEG preview,
        larger than thumbnail). Useful for ML evaluation and quality previews.
        Remote-transfer mode only.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        slot_number : int
            SD card slot number (1 or 2)

        content_id : int
            SDK content identifier from `listSDCardFiles` response

        file_id : int
            SDK file identifier from `listSDCardFiles` response (always `0` in contents-transfer mode)

        save_path : typing.Optional[str]
            Directory path on host PC to save the file

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CompressedDownloadResponse
            Screennail download accepted (async)

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.sd_card.download_screennail(
            camera_id="cameraId",
            slot_number=1,
            content_id=1,
            file_id=1,
        )
        """
        _response = self._raw_client.download_screennail(
            camera_id, slot_number, content_id, file_id, save_path=save_path, request_options=request_options
        )
        return _response.data


class AsyncSdCardClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSdCardClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSdCardClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSdCardClient
        """
        return self._raw_client

    async def list(
        self, camera_id: str, slot_number: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SdCardFileListResponse:
        """
        List files on the SD card. Requires `remote-transfer` or `contents` mode.
        Returns 400 if called in `remote` mode.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        slot_number : int
            SD card slot number (1 or 2)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SdCardFileListResponse
            File list retrieved

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.sd_card.list(
                camera_id="cameraId",
                slot_number=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(camera_id, slot_number, request_options=request_options)
        return _response.data

    async def download(
        self,
        camera_id: str,
        slot_number: int,
        content_id: int,
        file_id: int,
        *,
        save_path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncOperationResponse:
        """
        Initiates an async download of a specific file from the SD card to the host PC.
        Returns immediately; completion is signaled via the `downloadComplete` SSE event
        (remote/remote-transfer modes) or via filesystem polling (contents-transfer mode).

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        slot_number : int
            SD card slot number (1 or 2)

        content_id : int
            SDK content identifier from `listSDCardFiles` response

        file_id : int
            SDK file identifier from `listSDCardFiles` response (always `0` in contents-transfer mode)

        save_path : typing.Optional[str]
            Directory path on host PC to save the file

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncOperationResponse
            Download accepted (async)

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.sd_card.download(
                camera_id="cameraId",
                slot_number=1,
                content_id=1,
                file_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.download(
            camera_id, slot_number, content_id, file_id, save_path=save_path, request_options=request_options
        )
        return _response.data

    async def download_thumbnail(
        self,
        camera_id: str,
        slot_number: int,
        content_id: int,
        file_id: int,
        *,
        save_path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CompressedDownloadResponse:
        """
        Initiates an async download of the file's thumbnail (small JPEG preview).
        Used for fast file browser previews. Remote-transfer mode only.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        slot_number : int
            SD card slot number (1 or 2)

        content_id : int
            SDK content identifier from `listSDCardFiles` response

        file_id : int
            SDK file identifier from `listSDCardFiles` response (always `0` in contents-transfer mode)

        save_path : typing.Optional[str]
            Directory path on host PC to save the file

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CompressedDownloadResponse
            Thumbnail download accepted (async)

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.sd_card.download_thumbnail(
                camera_id="cameraId",
                slot_number=1,
                content_id=1,
                file_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.download_thumbnail(
            camera_id, slot_number, content_id, file_id, save_path=save_path, request_options=request_options
        )
        return _response.data

    async def download_screennail(
        self,
        camera_id: str,
        slot_number: int,
        content_id: int,
        file_id: int,
        *,
        save_path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CompressedDownloadResponse:
        """
        Initiates an async download of the file's screennail (medium JPEG preview,
        larger than thumbnail). Useful for ML evaluation and quality previews.
        Remote-transfer mode only.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        slot_number : int
            SD card slot number (1 or 2)

        content_id : int
            SDK content identifier from `listSDCardFiles` response

        file_id : int
            SDK file identifier from `listSDCardFiles` response (always `0` in contents-transfer mode)

        save_path : typing.Optional[str]
            Directory path on host PC to save the file

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CompressedDownloadResponse
            Screennail download accepted (async)

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.sd_card.download_screennail(
                camera_id="cameraId",
                slot_number=1,
                content_id=1,
                file_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.download_screennail(
            camera_id, slot_number, content_id, file_id, save_path=save_path, request_options=request_options
        )
        return _response.data
