# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.not_found_error import NotFoundError
from ..types.async_operation_response import AsyncOperationResponse
from ..types.compressed_download_response import CompressedDownloadResponse
from ..types.error_response import ErrorResponse
from ..types.sd_card_file_list_response import SdCardFileListResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawSdCardClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self, camera_id: str, slot_number: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SdCardFileListResponse]:
        """
        List files on the SD card. Requires `remote-transfer` or `contents` mode.
        Returns 400 if called in `remote` mode.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        slot_number : int
            SD card slot number (1 or 2)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SdCardFileListResponse]
            File list retrieved
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/sd-card/slot/{encode_path_param(slot_number)}/files",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SdCardFileListResponse,
                    parse_obj_as(
                        type_=SdCardFileListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def download(
        self,
        camera_id: str,
        slot_number: int,
        content_id: int,
        file_id: int,
        *,
        save_path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[AsyncOperationResponse]:
        """
        Initiates an async download of a specific file from the SD card to the host PC.
        Returns immediately; completion is signaled via the `downloadComplete` SSE event
        (remote/remote-transfer modes) or via filesystem polling (contents-transfer mode).

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        slot_number : int
            SD card slot number (1 or 2)

        content_id : int
            SDK content identifier from `listSDCardFiles` response

        file_id : int
            SDK file identifier from `listSDCardFiles` response (always `0` in contents-transfer mode)

        save_path : typing.Optional[str]
            Directory path on host PC to save the file

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AsyncOperationResponse]
            Download accepted (async)
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/sd-card/slot/{encode_path_param(slot_number)}/files/{encode_path_param(content_id)}/{encode_path_param(file_id)}/download",
            method="POST",
            json={
                "save_path": save_path,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AsyncOperationResponse,
                    parse_obj_as(
                        type_=AsyncOperationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def download_thumbnail(
        self,
        camera_id: str,
        slot_number: int,
        content_id: int,
        file_id: int,
        *,
        save_path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CompressedDownloadResponse]:
        """
        Initiates an async download of the file's thumbnail (small JPEG preview).
        Used for fast file browser previews. Remote-transfer mode only.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        slot_number : int
            SD card slot number (1 or 2)

        content_id : int
            SDK content identifier from `listSDCardFiles` response

        file_id : int
            SDK file identifier from `listSDCardFiles` response (always `0` in contents-transfer mode)

        save_path : typing.Optional[str]
            Directory path on host PC to save the file

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CompressedDownloadResponse]
            Thumbnail download accepted (async)
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/sd-card/slot/{encode_path_param(slot_number)}/files/{encode_path_param(content_id)}/{encode_path_param(file_id)}/thumbnail",
            method="POST",
            json={
                "save_path": save_path,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CompressedDownloadResponse,
                    parse_obj_as(
                        type_=CompressedDownloadResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def download_screennail(
        self,
        camera_id: str,
        slot_number: int,
        content_id: int,
        file_id: int,
        *,
        save_path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CompressedDownloadResponse]:
        """
        Initiates an async download of the file's screennail (medium JPEG preview,
        larger than thumbnail). Useful for ML evaluation and quality previews.
        Remote-transfer mode only.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        slot_number : int
            SD card slot number (1 or 2)

        content_id : int
            SDK content identifier from `listSDCardFiles` response

        file_id : int
            SDK file identifier from `listSDCardFiles` response (always `0` in contents-transfer mode)

        save_path : typing.Optional[str]
            Directory path on host PC to save the file

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CompressedDownloadResponse]
            Screennail download accepted (async)
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/sd-card/slot/{encode_path_param(slot_number)}/files/{encode_path_param(content_id)}/{encode_path_param(file_id)}/screennail",
            method="POST",
            json={
                "save_path": save_path,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CompressedDownloadResponse,
                    parse_obj_as(
                        type_=CompressedDownloadResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawSdCardClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self, camera_id: str, slot_number: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SdCardFileListResponse]:
        """
        List files on the SD card. Requires `remote-transfer` or `contents` mode.
        Returns 400 if called in `remote` mode.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        slot_number : int
            SD card slot number (1 or 2)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SdCardFileListResponse]
            File list retrieved
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/sd-card/slot/{encode_path_param(slot_number)}/files",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SdCardFileListResponse,
                    parse_obj_as(
                        type_=SdCardFileListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def download(
        self,
        camera_id: str,
        slot_number: int,
        content_id: int,
        file_id: int,
        *,
        save_path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[AsyncOperationResponse]:
        """
        Initiates an async download of a specific file from the SD card to the host PC.
        Returns immediately; completion is signaled via the `downloadComplete` SSE event
        (remote/remote-transfer modes) or via filesystem polling (contents-transfer mode).

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        slot_number : int
            SD card slot number (1 or 2)

        content_id : int
            SDK content identifier from `listSDCardFiles` response

        file_id : int
            SDK file identifier from `listSDCardFiles` response (always `0` in contents-transfer mode)

        save_path : typing.Optional[str]
            Directory path on host PC to save the file

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AsyncOperationResponse]
            Download accepted (async)
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/sd-card/slot/{encode_path_param(slot_number)}/files/{encode_path_param(content_id)}/{encode_path_param(file_id)}/download",
            method="POST",
            json={
                "save_path": save_path,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AsyncOperationResponse,
                    parse_obj_as(
                        type_=AsyncOperationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def download_thumbnail(
        self,
        camera_id: str,
        slot_number: int,
        content_id: int,
        file_id: int,
        *,
        save_path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CompressedDownloadResponse]:
        """
        Initiates an async download of the file's thumbnail (small JPEG preview).
        Used for fast file browser previews. Remote-transfer mode only.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        slot_number : int
            SD card slot number (1 or 2)

        content_id : int
            SDK content identifier from `listSDCardFiles` response

        file_id : int
            SDK file identifier from `listSDCardFiles` response (always `0` in contents-transfer mode)

        save_path : typing.Optional[str]
            Directory path on host PC to save the file

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CompressedDownloadResponse]
            Thumbnail download accepted (async)
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/sd-card/slot/{encode_path_param(slot_number)}/files/{encode_path_param(content_id)}/{encode_path_param(file_id)}/thumbnail",
            method="POST",
            json={
                "save_path": save_path,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CompressedDownloadResponse,
                    parse_obj_as(
                        type_=CompressedDownloadResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def download_screennail(
        self,
        camera_id: str,
        slot_number: int,
        content_id: int,
        file_id: int,
        *,
        save_path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CompressedDownloadResponse]:
        """
        Initiates an async download of the file's screennail (medium JPEG preview,
        larger than thumbnail). Useful for ML evaluation and quality previews.
        Remote-transfer mode only.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        slot_number : int
            SD card slot number (1 or 2)

        content_id : int
            SDK content identifier from `listSDCardFiles` response

        file_id : int
            SDK file identifier from `listSDCardFiles` response (always `0` in contents-transfer mode)

        save_path : typing.Optional[str]
            Directory path on host PC to save the file

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CompressedDownloadResponse]
            Screennail download accepted (async)
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/sd-card/slot/{encode_path_param(slot_number)}/files/{encode_path_param(content_id)}/{encode_path_param(file_id)}/screennail",
            method="POST",
            json={
                "save_path": save_path,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CompressedDownloadResponse,
                    parse_obj_as(
                        type_=CompressedDownloadResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
