# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.camera_response import CameraResponse
from ..types.get_all_properties_response import GetAllPropertiesResponse
from ..types.get_priority_key_response import GetPriorityKeyResponse
from ..types.get_property_response import GetPropertyResponse
from ..types.priority_key_setting import PriorityKeySetting
from ..types.property_name import PropertyName
from .raw_client import AsyncRawPropertiesClient, RawPropertiesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PropertiesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPropertiesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPropertiesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPropertiesClient
        """
        return self._raw_client

    def get(
        self, camera_id: str, property_name: PropertyName, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPropertyResponse:
        """
        Returns the current value, human-readable format, writability flag, and all
        values the camera currently accepts for this property.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        property_name : PropertyName
            Property name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPropertyResponse
            Property retrieved

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.properties.get(
            camera_id="cameraId",
            property_name="priority-key",
        )
        """
        _response = self._raw_client.get(camera_id, property_name, request_options=request_options)
        return _response.data

    def set(
        self,
        camera_id: str,
        property_name: PropertyName,
        *,
        value: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CameraResponse:
        """
        Set a camera property value. Accepts hex values (from GET response `available_values`)
        or human-readable strings (e.g. `"f/5.6"`, `"1/250"`, `"wide"`).

        The server validates against the camera's current available values and checks
        writability before sending to the SDK.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        property_name : PropertyName
            Property name

        value : str
            Hex value from `available_values` (e.g. `"0x1007d"`), human-readable
            string (e.g. `"1/125"`, `"f/5.6"`, `"wide"`), or decimal string.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Property set successfully

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.properties.set(
            camera_id="cameraId",
            property_name="priority-key",
            value="value",
        )
        """
        _response = self._raw_client.set(camera_id, property_name, value=value, request_options=request_options)
        return _response.data

    def get_all(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetAllPropertiesResponse:
        """
        Returns every property the camera currently reports, deduplicated by name
        (the SDK occasionally returns multiple internal entries for the same
        property — the server picks the entry that has values or is writable).

        ## Important: response shape differs from single-property GET

        The per-property entries here use a DIFFERENT shape than
        `getProperty` — see `BulkPropertyEntry` vs `PropertyData`. Highlights:

        - Field names: `current_value` / `current_hex_value` / `current_formatted`
          instead of `value` / `formatted`
        - `writable` is a real boolean here (not the stringified `"true"`/`"false"`
          you get from single GET)
        - `available_values` entries carry both numeric `value` and `hex_value`

        Use this endpoint for "load everything once" UI flows. Use single GET
        when you need just one property and want the consistent setter format.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAllPropertiesResponse
            All properties retrieved

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.properties.get_all(
            camera_id="cameraId",
        )
        """
        _response = self._raw_client.get_all(camera_id, request_options=request_options)
        return _response.data

    def get_priority_key(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPriorityKeyResponse:
        """
        Returns the current priority key setting (`pc-remote` or `camera-position`).

        **Note**: FX3 / cinema bodies do not implement `PriorityKeySettings` —
        GET returns empty data and SET returns SDK error `0x8402`. These bodies
        auto-enter PC Remote mode on USB.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPriorityKeyResponse
            Priority key retrieved

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.properties.get_priority_key(
            camera_id="cameraId",
        )
        """
        _response = self._raw_client.get_priority_key(camera_id, request_options=request_options)
        return _response.data

    def set_priority_key(
        self, camera_id: str, *, setting: PriorityKeySetting, request_options: typing.Optional[RequestOptions] = None
    ) -> CameraResponse:
        """
        Set the priority key. Must be `pc-remote` for the camera to accept remote
        property changes and shooting commands. Not supported on FX3 / cinema
        bodies (returns 400).

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        setting : PriorityKeySetting

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Priority key set

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.properties.set_priority_key(
            camera_id="cameraId",
            setting="pc-remote",
        )
        """
        _response = self._raw_client.set_priority_key(camera_id, setting=setting, request_options=request_options)
        return _response.data


class AsyncPropertiesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPropertiesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPropertiesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPropertiesClient
        """
        return self._raw_client

    async def get(
        self, camera_id: str, property_name: PropertyName, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPropertyResponse:
        """
        Returns the current value, human-readable format, writability flag, and all
        values the camera currently accepts for this property.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        property_name : PropertyName
            Property name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPropertyResponse
            Property retrieved

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.properties.get(
                camera_id="cameraId",
                property_name="priority-key",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(camera_id, property_name, request_options=request_options)
        return _response.data

    async def set(
        self,
        camera_id: str,
        property_name: PropertyName,
        *,
        value: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CameraResponse:
        """
        Set a camera property value. Accepts hex values (from GET response `available_values`)
        or human-readable strings (e.g. `"f/5.6"`, `"1/250"`, `"wide"`).

        The server validates against the camera's current available values and checks
        writability before sending to the SDK.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        property_name : PropertyName
            Property name

        value : str
            Hex value from `available_values` (e.g. `"0x1007d"`), human-readable
            string (e.g. `"1/125"`, `"f/5.6"`, `"wide"`), or decimal string.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Property set successfully

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.properties.set(
                camera_id="cameraId",
                property_name="priority-key",
                value="value",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.set(camera_id, property_name, value=value, request_options=request_options)
        return _response.data

    async def get_all(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetAllPropertiesResponse:
        """
        Returns every property the camera currently reports, deduplicated by name
        (the SDK occasionally returns multiple internal entries for the same
        property — the server picks the entry that has values or is writable).

        ## Important: response shape differs from single-property GET

        The per-property entries here use a DIFFERENT shape than
        `getProperty` — see `BulkPropertyEntry` vs `PropertyData`. Highlights:

        - Field names: `current_value` / `current_hex_value` / `current_formatted`
          instead of `value` / `formatted`
        - `writable` is a real boolean here (not the stringified `"true"`/`"false"`
          you get from single GET)
        - `available_values` entries carry both numeric `value` and `hex_value`

        Use this endpoint for "load everything once" UI flows. Use single GET
        when you need just one property and want the consistent setter format.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAllPropertiesResponse
            All properties retrieved

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.properties.get_all(
                camera_id="cameraId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_all(camera_id, request_options=request_options)
        return _response.data

    async def get_priority_key(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPriorityKeyResponse:
        """
        Returns the current priority key setting (`pc-remote` or `camera-position`).

        **Note**: FX3 / cinema bodies do not implement `PriorityKeySettings` —
        GET returns empty data and SET returns SDK error `0x8402`. These bodies
        auto-enter PC Remote mode on USB.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPriorityKeyResponse
            Priority key retrieved

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.properties.get_priority_key(
                camera_id="cameraId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_priority_key(camera_id, request_options=request_options)
        return _response.data

    async def set_priority_key(
        self, camera_id: str, *, setting: PriorityKeySetting, request_options: typing.Optional[RequestOptions] = None
    ) -> CameraResponse:
        """
        Set the priority key. Must be `pc-remote` for the camera to accept remote
        property changes and shooting commands. Not supported on FX3 / cinema
        bodies (returns 400).

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        setting : PriorityKeySetting

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Priority key set

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.properties.set_priority_key(
                camera_id="cameraId",
                setting="pc-remote",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.set_priority_key(camera_id, setting=setting, request_options=request_options)
        return _response.data
