# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        AsyncOperationResponse,
        AvailableValue,
        BulkAvailableValue,
        BulkPropertiesData,
        BulkPropertyEntry,
        CameraInfo,
        CameraInfoConnectionType,
        CameraListResponse,
        CameraResponse,
        CameraSummary,
        CompressedDownloadResponse,
        CompressedDownloadResponseType,
        ConnectionMode,
        ConnectionStatusResponse,
        ConnectionStatusResponseData,
        ErrorResponse,
        GetAllPropertiesResponse,
        GetLiveViewStatusResponse,
        GetOsdStatusResponse,
        GetPriorityKeyResponse,
        GetPropertyResponse,
        GetSaveInfoResponse,
        LiveViewStatus,
        LogEntry,
        LogEntryLevel,
        LutImportResponse,
        LutImportResponseData,
        OsdStatus,
        PriorityKeyData,
        PriorityKeySetting,
        PropertyData,
        PropertyName,
        SaveInfoData,
        SdCardDownloadRequest,
        SdCardFile,
        SdCardFileListResponse,
        ServerLogsResponse,
        ServerStatus,
        ServerStatusCameras,
        ServerStatusServer,
        ServerStatusServerPlatform,
        SettingsFileListResponse,
        SettingsFileRequest,
        ShutdownServerResponse,
        ZoomDirectionalRequest,
        ZoomDirectionalRequestDirection,
        ZoomDirectionalRequestSpeed,
        ZoomRequest,
        ZoomSignedSpeedRequest,
    )
    from .errors import BadRequestError, InternalServerError, NotFoundError
    from . import actions, cameras, live_view, properties, sd_card, server, settings
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .actions import ShutterRequestAction
    from .cameras import ConnectionRequestReconnecting
    from .client import AlphaSDKClient, AsyncAlphaSDKClient
    from .environment import AlphaSDKClientEnvironment
    from .server import LogsServerRequestLevel
_dynamic_imports: typing.Dict[str, str] = {
    "AlphaSDKClient": ".client",
    "AlphaSDKClientEnvironment": ".environment",
    "AsyncAlphaSDKClient": ".client",
    "AsyncOperationResponse": ".types",
    "AvailableValue": ".types",
    "BadRequestError": ".errors",
    "BulkAvailableValue": ".types",
    "BulkPropertiesData": ".types",
    "BulkPropertyEntry": ".types",
    "CameraInfo": ".types",
    "CameraInfoConnectionType": ".types",
    "CameraListResponse": ".types",
    "CameraResponse": ".types",
    "CameraSummary": ".types",
    "CompressedDownloadResponse": ".types",
    "CompressedDownloadResponseType": ".types",
    "ConnectionMode": ".types",
    "ConnectionRequestReconnecting": ".cameras",
    "ConnectionStatusResponse": ".types",
    "ConnectionStatusResponseData": ".types",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "ErrorResponse": ".types",
    "GetAllPropertiesResponse": ".types",
    "GetLiveViewStatusResponse": ".types",
    "GetOsdStatusResponse": ".types",
    "GetPriorityKeyResponse": ".types",
    "GetPropertyResponse": ".types",
    "GetSaveInfoResponse": ".types",
    "InternalServerError": ".errors",
    "LiveViewStatus": ".types",
    "LogEntry": ".types",
    "LogEntryLevel": ".types",
    "LogsServerRequestLevel": ".server",
    "LutImportResponse": ".types",
    "LutImportResponseData": ".types",
    "NotFoundError": ".errors",
    "OsdStatus": ".types",
    "PriorityKeyData": ".types",
    "PriorityKeySetting": ".types",
    "PropertyData": ".types",
    "PropertyName": ".types",
    "SaveInfoData": ".types",
    "SdCardDownloadRequest": ".types",
    "SdCardFile": ".types",
    "SdCardFileListResponse": ".types",
    "ServerLogsResponse": ".types",
    "ServerStatus": ".types",
    "ServerStatusCameras": ".types",
    "ServerStatusServer": ".types",
    "ServerStatusServerPlatform": ".types",
    "SettingsFileListResponse": ".types",
    "SettingsFileRequest": ".types",
    "ShutdownServerResponse": ".types",
    "ShutterRequestAction": ".actions",
    "ZoomDirectionalRequest": ".types",
    "ZoomDirectionalRequestDirection": ".types",
    "ZoomDirectionalRequestSpeed": ".types",
    "ZoomRequest": ".types",
    "ZoomSignedSpeedRequest": ".types",
    "actions": ".actions",
    "cameras": ".cameras",
    "live_view": ".live_view",
    "properties": ".properties",
    "sd_card": ".sd_card",
    "server": ".server",
    "settings": ".settings",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AlphaSDKClient",
    "AlphaSDKClientEnvironment",
    "AsyncAlphaSDKClient",
    "AsyncOperationResponse",
    "AvailableValue",
    "BadRequestError",
    "BulkAvailableValue",
    "BulkPropertiesData",
    "BulkPropertyEntry",
    "CameraInfo",
    "CameraInfoConnectionType",
    "CameraListResponse",
    "CameraResponse",
    "CameraSummary",
    "CompressedDownloadResponse",
    "CompressedDownloadResponseType",
    "ConnectionMode",
    "ConnectionRequestReconnecting",
    "ConnectionStatusResponse",
    "ConnectionStatusResponseData",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "ErrorResponse",
    "GetAllPropertiesResponse",
    "GetLiveViewStatusResponse",
    "GetOsdStatusResponse",
    "GetPriorityKeyResponse",
    "GetPropertyResponse",
    "GetSaveInfoResponse",
    "InternalServerError",
    "LiveViewStatus",
    "LogEntry",
    "LogEntryLevel",
    "LogsServerRequestLevel",
    "LutImportResponse",
    "LutImportResponseData",
    "NotFoundError",
    "OsdStatus",
    "PriorityKeyData",
    "PriorityKeySetting",
    "PropertyData",
    "PropertyName",
    "SaveInfoData",
    "SdCardDownloadRequest",
    "SdCardFile",
    "SdCardFileListResponse",
    "ServerLogsResponse",
    "ServerStatus",
    "ServerStatusCameras",
    "ServerStatusServer",
    "ServerStatusServerPlatform",
    "SettingsFileListResponse",
    "SettingsFileRequest",
    "ShutdownServerResponse",
    "ShutterRequestAction",
    "ZoomDirectionalRequest",
    "ZoomDirectionalRequestDirection",
    "ZoomDirectionalRequestSpeed",
    "ZoomRequest",
    "ZoomSignedSpeedRequest",
    "actions",
    "cameras",
    "live_view",
    "properties",
    "sd_card",
    "server",
    "settings",
]
