# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import httpx
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.logging import LogConfig, Logger
from .environment import AlphaSDKClientEnvironment

if typing.TYPE_CHECKING:
    from .actions.client import ActionsClient, AsyncActionsClient
    from .cameras.client import AsyncCamerasClient, CamerasClient
    from .live_view.client import AsyncLiveViewClient, LiveViewClient
    from .properties.client import AsyncPropertiesClient, PropertiesClient
    from .sd_card.client import AsyncSdCardClient, SdCardClient
    from .server.client import AsyncServerClient, ServerClient
    from .settings.client import AsyncSettingsClient, SettingsClient


class AlphaSDKClient:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : AlphaSDKClientEnvironment
        The environment to use for requests from the client. from .environment import AlphaSDKClientEnvironment



        Defaults to AlphaSDKClientEnvironment.DEFAULT



    host : typing.Optional[str]
        Server URL variable for 'host'. Defaults to 'localhost'.

    port : typing.Optional[str]
        Server URL variable for 'port'. Defaults to '8080'.

    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from alpha_sdk_client import AlphaSDKClient

    client = AlphaSDKClient()
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: AlphaSDKClientEnvironment = AlphaSDKClientEnvironment.DEFAULT,
        host: typing.Optional[str] = None,
        port: typing.Optional[str] = None,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        if host is not None or port is not None:
            _host = host if host is not None else "localhost"
            _port = port if port is not None else "8080"
            base_url = "http://{host}:{port}".format(host=_host, port=_port)
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            logging=logging,
        )
        self._server: typing.Optional[ServerClient] = None
        self._cameras: typing.Optional[CamerasClient] = None
        self._properties: typing.Optional[PropertiesClient] = None
        self._actions: typing.Optional[ActionsClient] = None
        self._live_view: typing.Optional[LiveViewClient] = None
        self._sd_card: typing.Optional[SdCardClient] = None
        self._settings: typing.Optional[SettingsClient] = None

    @property
    def server(self):
        if self._server is None:
            from .server.client import ServerClient  # noqa: E402

            self._server = ServerClient(client_wrapper=self._client_wrapper)
        return self._server

    @property
    def cameras(self):
        if self._cameras is None:
            from .cameras.client import CamerasClient  # noqa: E402

            self._cameras = CamerasClient(client_wrapper=self._client_wrapper)
        return self._cameras

    @property
    def properties(self):
        if self._properties is None:
            from .properties.client import PropertiesClient  # noqa: E402

            self._properties = PropertiesClient(client_wrapper=self._client_wrapper)
        return self._properties

    @property
    def actions(self):
        if self._actions is None:
            from .actions.client import ActionsClient  # noqa: E402

            self._actions = ActionsClient(client_wrapper=self._client_wrapper)
        return self._actions

    @property
    def live_view(self):
        if self._live_view is None:
            from .live_view.client import LiveViewClient  # noqa: E402

            self._live_view = LiveViewClient(client_wrapper=self._client_wrapper)
        return self._live_view

    @property
    def sd_card(self):
        if self._sd_card is None:
            from .sd_card.client import SdCardClient  # noqa: E402

            self._sd_card = SdCardClient(client_wrapper=self._client_wrapper)
        return self._sd_card

    @property
    def settings(self):
        if self._settings is None:
            from .settings.client import SettingsClient  # noqa: E402

            self._settings = SettingsClient(client_wrapper=self._client_wrapper)
        return self._settings


def _make_default_async_client(
    timeout: typing.Optional[float],
    follow_redirects: typing.Optional[bool],
) -> httpx.AsyncClient:
    try:
        import httpx_aiohttp  # type: ignore[import-not-found]
    except ImportError:
        pass
    else:
        if follow_redirects is not None:
            return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout, follow_redirects=follow_redirects)
        return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout)

    if follow_redirects is not None:
        return httpx.AsyncClient(timeout=timeout, follow_redirects=follow_redirects)
    return httpx.AsyncClient(timeout=timeout)


class AsyncAlphaSDKClient:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : AlphaSDKClientEnvironment
        The environment to use for requests from the client. from .environment import AlphaSDKClientEnvironment



        Defaults to AlphaSDKClientEnvironment.DEFAULT



    host : typing.Optional[str]
        Server URL variable for 'host'. Defaults to 'localhost'.

    port : typing.Optional[str]
        Server URL variable for 'port'. Defaults to '8080'.

    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from alpha_sdk_client import AsyncAlphaSDKClient

    client = AsyncAlphaSDKClient()
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: AlphaSDKClientEnvironment = AlphaSDKClientEnvironment.DEFAULT,
        host: typing.Optional[str] = None,
        port: typing.Optional[str] = None,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        if host is not None or port is not None:
            _host = host if host is not None else "localhost"
            _port = port if port is not None else "8080"
            base_url = "http://{host}:{port}".format(host=_host, port=_port)
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else _make_default_async_client(timeout=_defaulted_timeout, follow_redirects=follow_redirects),
            timeout=_defaulted_timeout,
            logging=logging,
        )
        self._server: typing.Optional[AsyncServerClient] = None
        self._cameras: typing.Optional[AsyncCamerasClient] = None
        self._properties: typing.Optional[AsyncPropertiesClient] = None
        self._actions: typing.Optional[AsyncActionsClient] = None
        self._live_view: typing.Optional[AsyncLiveViewClient] = None
        self._sd_card: typing.Optional[AsyncSdCardClient] = None
        self._settings: typing.Optional[AsyncSettingsClient] = None

    @property
    def server(self):
        if self._server is None:
            from .server.client import AsyncServerClient  # noqa: E402

            self._server = AsyncServerClient(client_wrapper=self._client_wrapper)
        return self._server

    @property
    def cameras(self):
        if self._cameras is None:
            from .cameras.client import AsyncCamerasClient  # noqa: E402

            self._cameras = AsyncCamerasClient(client_wrapper=self._client_wrapper)
        return self._cameras

    @property
    def properties(self):
        if self._properties is None:
            from .properties.client import AsyncPropertiesClient  # noqa: E402

            self._properties = AsyncPropertiesClient(client_wrapper=self._client_wrapper)
        return self._properties

    @property
    def actions(self):
        if self._actions is None:
            from .actions.client import AsyncActionsClient  # noqa: E402

            self._actions = AsyncActionsClient(client_wrapper=self._client_wrapper)
        return self._actions

    @property
    def live_view(self):
        if self._live_view is None:
            from .live_view.client import AsyncLiveViewClient  # noqa: E402

            self._live_view = AsyncLiveViewClient(client_wrapper=self._client_wrapper)
        return self._live_view

    @property
    def sd_card(self):
        if self._sd_card is None:
            from .sd_card.client import AsyncSdCardClient  # noqa: E402

            self._sd_card = AsyncSdCardClient(client_wrapper=self._client_wrapper)
        return self._sd_card

    @property
    def settings(self):
        if self._settings is None:
            from .settings.client import AsyncSettingsClient  # noqa: E402

            self._settings = AsyncSettingsClient(client_wrapper=self._client_wrapper)
        return self._settings


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: AlphaSDKClientEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
