# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.camera_response import CameraResponse
from ..types.get_live_view_status_response import GetLiveViewStatusResponse
from ..types.get_osd_status_response import GetOsdStatusResponse
from .raw_client import AsyncRawLiveViewClient, RawLiveViewClient


class LiveViewClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawLiveViewClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawLiveViewClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawLiveViewClient
        """
        return self._raw_client

    def enable(self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> CameraResponse:
        """
        Sends the SDK `Setting_Key_EnableLiveView` command to the camera.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Live view enabled

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.live_view.enable(
            camera_id="cameraId",
        )
        """
        _response = self._raw_client.enable(camera_id, request_options=request_options)
        return _response.data

    def disable(self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> CameraResponse:
        """
        Sends the SDK `Setting_Key_DisableLiveView` command. Stops live view streaming if it was running.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Live view disabled

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.live_view.disable(
            camera_id="cameraId",
        )
        """
        _response = self._raw_client.disable(camera_id, request_options=request_options)
        return _response.data

    def get_status(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetLiveViewStatusResponse:
        """
        Returns whether live view is `enabled` (camera setting) and whether
        the server is currently `streaming` frames from the camera.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetLiveViewStatusResponse
            Live view status

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.live_view.get_status(
            camera_id="cameraId",
        )
        """
        _response = self._raw_client.get_status(camera_id, request_options=request_options)
        return _response.data

    def start(self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> CameraResponse:
        """
        Starts the frame capture worker thread. Auto-enables live view if disabled.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Streaming started

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.live_view.start(
            camera_id="cameraId",
        )
        """
        _response = self._raw_client.start(camera_id, request_options=request_options)
        return _response.data

    def stop(self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> CameraResponse:
        """
        Stops the frame capture worker thread. Live view itself remains enabled on the camera unless you also call `disableLiveView`.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Streaming stopped

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.live_view.stop(
            camera_id="cameraId",
        )
        """
        _response = self._raw_client.stop(camera_id, request_options=request_options)
        return _response.data

    def get_frame(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[bytes]:
        """
        Returns the latest live view frame as a JPEG image. Streaming must be
        started first via `liveView.start`. Poll this endpoint at ~15 fps
        (every ~66 ms) to render a live preview.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            JPEG frame

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.live_view.get_frame(
            camera_id="cameraId",
        )
        """
        with self._raw_client.get_frame(camera_id, request_options=request_options) as r:
            yield from r.data

    def enable_osd(self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> CameraResponse:
        """
        Enable On-Screen Display overlay via `CrDeviceProperty_OSDImageMode`.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            OSD enabled

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.live_view.enable_osd(
            camera_id="cameraId",
        )
        """
        _response = self._raw_client.enable_osd(camera_id, request_options=request_options)
        return _response.data

    def disable_osd(self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> CameraResponse:
        """
        Disables the camera's OSD overlay. Subsequent live view frames will not include UI overlays.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            OSD disabled

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.live_view.disable_osd(
            camera_id="cameraId",
        )
        """
        _response = self._raw_client.disable_osd(camera_id, request_options=request_options)
        return _response.data

    def get_osd_status(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetOsdStatusResponse:
        """
        Returns whether OSD is `supported` on this camera body and whether it is currently `enabled`.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetOsdStatusResponse
            OSD status

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.live_view.get_osd_status(
            camera_id="cameraId",
        )
        """
        _response = self._raw_client.get_osd_status(camera_id, request_options=request_options)
        return _response.data

    def get_osd_frame(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[bytes]:
        """
        Returns a composited JPEG with live view image + camera UI overlay.
        Same polling pattern as `liveView.getFrame` — OSD must be enabled
        first via `liveView.enableOSD`.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            Composited JPEG frame

        Examples
        --------
        from alpha_sdk_client import AlphaSDKClient

        client = AlphaSDKClient()
        client.live_view.get_osd_frame(
            camera_id="cameraId",
        )
        """
        with self._raw_client.get_osd_frame(camera_id, request_options=request_options) as r:
            yield from r.data


class AsyncLiveViewClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawLiveViewClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawLiveViewClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawLiveViewClient
        """
        return self._raw_client

    async def enable(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CameraResponse:
        """
        Sends the SDK `Setting_Key_EnableLiveView` command to the camera.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Live view enabled

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.live_view.enable(
                camera_id="cameraId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.enable(camera_id, request_options=request_options)
        return _response.data

    async def disable(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CameraResponse:
        """
        Sends the SDK `Setting_Key_DisableLiveView` command. Stops live view streaming if it was running.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Live view disabled

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.live_view.disable(
                camera_id="cameraId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.disable(camera_id, request_options=request_options)
        return _response.data

    async def get_status(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetLiveViewStatusResponse:
        """
        Returns whether live view is `enabled` (camera setting) and whether
        the server is currently `streaming` frames from the camera.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetLiveViewStatusResponse
            Live view status

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.live_view.get_status(
                camera_id="cameraId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_status(camera_id, request_options=request_options)
        return _response.data

    async def start(self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> CameraResponse:
        """
        Starts the frame capture worker thread. Auto-enables live view if disabled.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Streaming started

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.live_view.start(
                camera_id="cameraId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.start(camera_id, request_options=request_options)
        return _response.data

    async def stop(self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> CameraResponse:
        """
        Stops the frame capture worker thread. Live view itself remains enabled on the camera unless you also call `disableLiveView`.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            Streaming stopped

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.live_view.stop(
                camera_id="cameraId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.stop(camera_id, request_options=request_options)
        return _response.data

    async def get_frame(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[bytes]:
        """
        Returns the latest live view frame as a JPEG image. Streaming must be
        started first via `liveView.start`. Poll this endpoint at ~15 fps
        (every ~66 ms) to render a live preview.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            JPEG frame

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.live_view.get_frame(
                camera_id="cameraId",
            )


        asyncio.run(main())
        """
        async with self._raw_client.get_frame(camera_id, request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk

    async def enable_osd(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CameraResponse:
        """
        Enable On-Screen Display overlay via `CrDeviceProperty_OSDImageMode`.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            OSD enabled

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.live_view.enable_osd(
                camera_id="cameraId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.enable_osd(camera_id, request_options=request_options)
        return _response.data

    async def disable_osd(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CameraResponse:
        """
        Disables the camera's OSD overlay. Subsequent live view frames will not include UI overlays.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CameraResponse
            OSD disabled

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.live_view.disable_osd(
                camera_id="cameraId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.disable_osd(camera_id, request_options=request_options)
        return _response.data

    async def get_osd_status(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetOsdStatusResponse:
        """
        Returns whether OSD is `supported` on this camera body and whether it is currently `enabled`.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetOsdStatusResponse
            OSD status

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.live_view.get_osd_status(
                camera_id="cameraId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_osd_status(camera_id, request_options=request_options)
        return _response.data

    async def get_osd_frame(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[bytes]:
        """
        Returns a composited JPEG with live view image + camera UI overlay.
        Same polling pattern as `liveView.getFrame` — OSD must be enabled
        first via `liveView.enableOSD`.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            Composited JPEG frame

        Examples
        --------
        import asyncio

        from alpha_sdk_client import AsyncAlphaSDKClient

        client = AsyncAlphaSDKClient()


        async def main() -> None:
            await client.live_view.get_osd_frame(
                camera_id="cameraId",
            )


        asyncio.run(main())
        """
        async with self._raw_client.get_osd_frame(camera_id, request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk
