# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..types.camera_response import CameraResponse
from ..types.error_response import ErrorResponse
from ..types.get_save_info_response import GetSaveInfoResponse
from ..types.lut_import_response import LutImportResponse
from ..types.settings_file_list_response import SettingsFileListResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawSettingsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_save_info(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GetSaveInfoResponse]:
        """
        Returns the current save directory, filename prefix, and start number for auto-transferred images.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetSaveInfoResponse]
            Save info retrieved
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/settings/save-info",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetSaveInfoResponse,
                    parse_obj_as(
                        type_=GetSaveInfoResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def set_save_info(
        self,
        camera_id: str,
        *,
        path: typing.Optional[str] = OMIT,
        prefix: typing.Optional[str] = OMIT,
        start_no: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CameraResponse]:
        """
        Configure the save directory, filename prefix, and start number.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        path : typing.Optional[str]
            Directory path on host PC

        prefix : typing.Optional[str]
            Filename prefix

        start_no : typing.Optional[int]
            Starting file number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CameraResponse]
            Save info set
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/settings/save-info",
            method="PUT",
            json={
                "path": path,
                "prefix": prefix,
                "startNo": start_no,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CameraResponse,
                    parse_obj_as(
                        type_=CameraResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def download(
        self,
        camera_id: str,
        *,
        filename: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CameraResponse]:
        """
        Download the camera's current settings to a file on the host PC.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        filename : typing.Optional[str]
            Settings filename (e.g. `CUMSET.DAT`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CameraResponse]
            Settings file saved
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/settings/download",
            method="POST",
            json={
                "filename": filename,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CameraResponse,
                    parse_obj_as(
                        type_=CameraResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def upload(
        self,
        camera_id: str,
        *,
        filename: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CameraResponse]:
        """
        Upload a previously saved settings file back to the camera.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        filename : typing.Optional[str]
            Settings filename (e.g. `CUMSET.DAT`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CameraResponse]
            Settings uploaded to camera
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/settings/upload",
            method="POST",
            json={
                "filename": filename,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CameraResponse,
                    parse_obj_as(
                        type_=CameraResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_files(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SettingsFileListResponse]:
        """
        Lists camera settings files (`*.DAT`) previously saved to the host PC via `downloadCameraSettings`.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SettingsFileListResponse]
            Settings file list
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/settings/files",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SettingsFileListResponse,
                    parse_obj_as(
                        type_=SettingsFileListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def import_lut(
        self,
        camera_id: str,
        *,
        file_path: str,
        slot: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[LutImportResponse]:
        """
        Initiates an async import of a `.cube` LUT file from the host filesystem
        into one of the camera's user LUT slots (1–16). CineEI / cinema bodies only.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        file_path : str
            Absolute or working-directory-relative path to a `.cube` file on the host

        slot : typing.Optional[int]
            Camera user LUT slot to import into

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[LutImportResponse]
            LUT import accepted (async)
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/lut/import",
            method="POST",
            json={
                "filePath": file_path,
                "slot": slot,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    LutImportResponse,
                    parse_obj_as(
                        type_=LutImportResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawSettingsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_save_info(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GetSaveInfoResponse]:
        """
        Returns the current save directory, filename prefix, and start number for auto-transferred images.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetSaveInfoResponse]
            Save info retrieved
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/settings/save-info",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetSaveInfoResponse,
                    parse_obj_as(
                        type_=GetSaveInfoResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def set_save_info(
        self,
        camera_id: str,
        *,
        path: typing.Optional[str] = OMIT,
        prefix: typing.Optional[str] = OMIT,
        start_no: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CameraResponse]:
        """
        Configure the save directory, filename prefix, and start number.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        path : typing.Optional[str]
            Directory path on host PC

        prefix : typing.Optional[str]
            Filename prefix

        start_no : typing.Optional[int]
            Starting file number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CameraResponse]
            Save info set
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/settings/save-info",
            method="PUT",
            json={
                "path": path,
                "prefix": prefix,
                "startNo": start_no,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CameraResponse,
                    parse_obj_as(
                        type_=CameraResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def download(
        self,
        camera_id: str,
        *,
        filename: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CameraResponse]:
        """
        Download the camera's current settings to a file on the host PC.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        filename : typing.Optional[str]
            Settings filename (e.g. `CUMSET.DAT`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CameraResponse]
            Settings file saved
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/settings/download",
            method="POST",
            json={
                "filename": filename,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CameraResponse,
                    parse_obj_as(
                        type_=CameraResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def upload(
        self,
        camera_id: str,
        *,
        filename: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CameraResponse]:
        """
        Upload a previously saved settings file back to the camera.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        filename : typing.Optional[str]
            Settings filename (e.g. `CUMSET.DAT`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CameraResponse]
            Settings uploaded to camera
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/settings/upload",
            method="POST",
            json={
                "filename": filename,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CameraResponse,
                    parse_obj_as(
                        type_=CameraResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_files(
        self, camera_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SettingsFileListResponse]:
        """
        Lists camera settings files (`*.DAT`) previously saved to the host PC via `downloadCameraSettings`.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SettingsFileListResponse]
            Settings file list
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/settings/files",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SettingsFileListResponse,
                    parse_obj_as(
                        type_=SettingsFileListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def import_lut(
        self,
        camera_id: str,
        *,
        file_path: str,
        slot: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[LutImportResponse]:
        """
        Initiates an async import of a `.cube` LUT file from the host filesystem
        into one of the camera's user LUT slots (1–16). CineEI / cinema bodies only.

        Parameters
        ----------
        camera_id : str
            Camera identifier (e.g. `D10F60149B0C`)

        file_path : str
            Absolute or working-directory-relative path to a `.cube` file on the host

        slot : typing.Optional[int]
            Camera user LUT slot to import into

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[LutImportResponse]
            LUT import accepted (async)
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/cameras/{encode_path_param(camera_id)}/lut/import",
            method="POST",
            json={
                "filePath": file_path,
                "slot": slot,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    LutImportResponse,
                    parse_obj_as(
                        type_=LutImportResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
