# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .async_operation_response import AsyncOperationResponse
    from .available_value import AvailableValue
    from .bulk_available_value import BulkAvailableValue
    from .bulk_properties_data import BulkPropertiesData
    from .bulk_property_entry import BulkPropertyEntry
    from .camera_info import CameraInfo
    from .camera_info_connection_type import CameraInfoConnectionType
    from .camera_list_response import CameraListResponse
    from .camera_response import CameraResponse
    from .camera_summary import CameraSummary
    from .compressed_download_response import CompressedDownloadResponse
    from .compressed_download_response_type import CompressedDownloadResponseType
    from .connection_mode import ConnectionMode
    from .connection_status_response import ConnectionStatusResponse
    from .connection_status_response_data import ConnectionStatusResponseData
    from .error_response import ErrorResponse
    from .get_all_properties_response import GetAllPropertiesResponse
    from .get_live_view_status_response import GetLiveViewStatusResponse
    from .get_osd_status_response import GetOsdStatusResponse
    from .get_priority_key_response import GetPriorityKeyResponse
    from .get_property_response import GetPropertyResponse
    from .get_save_info_response import GetSaveInfoResponse
    from .live_view_status import LiveViewStatus
    from .log_entry import LogEntry
    from .log_entry_level import LogEntryLevel
    from .lut_import_response import LutImportResponse
    from .lut_import_response_data import LutImportResponseData
    from .osd_status import OsdStatus
    from .priority_key_data import PriorityKeyData
    from .priority_key_setting import PriorityKeySetting
    from .property_data import PropertyData
    from .property_name import PropertyName
    from .save_info_data import SaveInfoData
    from .sd_card_download_request import SdCardDownloadRequest
    from .sd_card_file import SdCardFile
    from .sd_card_file_list_response import SdCardFileListResponse
    from .server_logs_response import ServerLogsResponse
    from .server_status import ServerStatus
    from .server_status_cameras import ServerStatusCameras
    from .server_status_server import ServerStatusServer
    from .server_status_server_platform import ServerStatusServerPlatform
    from .settings_file_list_response import SettingsFileListResponse
    from .settings_file_request import SettingsFileRequest
    from .shutdown_server_response import ShutdownServerResponse
    from .zoom_directional_request import ZoomDirectionalRequest
    from .zoom_directional_request_direction import ZoomDirectionalRequestDirection
    from .zoom_directional_request_speed import ZoomDirectionalRequestSpeed
    from .zoom_request import ZoomRequest
    from .zoom_signed_speed_request import ZoomSignedSpeedRequest
_dynamic_imports: typing.Dict[str, str] = {
    "AsyncOperationResponse": ".async_operation_response",
    "AvailableValue": ".available_value",
    "BulkAvailableValue": ".bulk_available_value",
    "BulkPropertiesData": ".bulk_properties_data",
    "BulkPropertyEntry": ".bulk_property_entry",
    "CameraInfo": ".camera_info",
    "CameraInfoConnectionType": ".camera_info_connection_type",
    "CameraListResponse": ".camera_list_response",
    "CameraResponse": ".camera_response",
    "CameraSummary": ".camera_summary",
    "CompressedDownloadResponse": ".compressed_download_response",
    "CompressedDownloadResponseType": ".compressed_download_response_type",
    "ConnectionMode": ".connection_mode",
    "ConnectionStatusResponse": ".connection_status_response",
    "ConnectionStatusResponseData": ".connection_status_response_data",
    "ErrorResponse": ".error_response",
    "GetAllPropertiesResponse": ".get_all_properties_response",
    "GetLiveViewStatusResponse": ".get_live_view_status_response",
    "GetOsdStatusResponse": ".get_osd_status_response",
    "GetPriorityKeyResponse": ".get_priority_key_response",
    "GetPropertyResponse": ".get_property_response",
    "GetSaveInfoResponse": ".get_save_info_response",
    "LiveViewStatus": ".live_view_status",
    "LogEntry": ".log_entry",
    "LogEntryLevel": ".log_entry_level",
    "LutImportResponse": ".lut_import_response",
    "LutImportResponseData": ".lut_import_response_data",
    "OsdStatus": ".osd_status",
    "PriorityKeyData": ".priority_key_data",
    "PriorityKeySetting": ".priority_key_setting",
    "PropertyData": ".property_data",
    "PropertyName": ".property_name",
    "SaveInfoData": ".save_info_data",
    "SdCardDownloadRequest": ".sd_card_download_request",
    "SdCardFile": ".sd_card_file",
    "SdCardFileListResponse": ".sd_card_file_list_response",
    "ServerLogsResponse": ".server_logs_response",
    "ServerStatus": ".server_status",
    "ServerStatusCameras": ".server_status_cameras",
    "ServerStatusServer": ".server_status_server",
    "ServerStatusServerPlatform": ".server_status_server_platform",
    "SettingsFileListResponse": ".settings_file_list_response",
    "SettingsFileRequest": ".settings_file_request",
    "ShutdownServerResponse": ".shutdown_server_response",
    "ZoomDirectionalRequest": ".zoom_directional_request",
    "ZoomDirectionalRequestDirection": ".zoom_directional_request_direction",
    "ZoomDirectionalRequestSpeed": ".zoom_directional_request_speed",
    "ZoomRequest": ".zoom_request",
    "ZoomSignedSpeedRequest": ".zoom_signed_speed_request",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AsyncOperationResponse",
    "AvailableValue",
    "BulkAvailableValue",
    "BulkPropertiesData",
    "BulkPropertyEntry",
    "CameraInfo",
    "CameraInfoConnectionType",
    "CameraListResponse",
    "CameraResponse",
    "CameraSummary",
    "CompressedDownloadResponse",
    "CompressedDownloadResponseType",
    "ConnectionMode",
    "ConnectionStatusResponse",
    "ConnectionStatusResponseData",
    "ErrorResponse",
    "GetAllPropertiesResponse",
    "GetLiveViewStatusResponse",
    "GetOsdStatusResponse",
    "GetPriorityKeyResponse",
    "GetPropertyResponse",
    "GetSaveInfoResponse",
    "LiveViewStatus",
    "LogEntry",
    "LogEntryLevel",
    "LutImportResponse",
    "LutImportResponseData",
    "OsdStatus",
    "PriorityKeyData",
    "PriorityKeySetting",
    "PropertyData",
    "PropertyName",
    "SaveInfoData",
    "SdCardDownloadRequest",
    "SdCardFile",
    "SdCardFileListResponse",
    "ServerLogsResponse",
    "ServerStatus",
    "ServerStatusCameras",
    "ServerStatusServer",
    "ServerStatusServerPlatform",
    "SettingsFileListResponse",
    "SettingsFileRequest",
    "ShutdownServerResponse",
    "ZoomDirectionalRequest",
    "ZoomDirectionalRequestDirection",
    "ZoomDirectionalRequestSpeed",
    "ZoomRequest",
    "ZoomSignedSpeedRequest",
]
