# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AsyncOperationResponse(UniversalBaseModel):
    """
    Generic envelope for async operations that have been accepted but not yet completed.
    Watch for the corresponding SSE event (`downloadComplete`, `transferProgress`) to
    learn when the operation finishes.
    """

    success: bool
    message: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
