# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AvailableValue(UniversalBaseModel):
    """
    Single entry inside the `available_values` array returned by single-GET
    property responses. Contains only the hex value (as a string) and the
    formatted label — no separate numeric value field. The bulk endpoint
    uses `BulkAvailableValue`, which is a different shape.
    """

    value: str = pydantic.Field()
    """
    Hex value to use in SET requests
    """

    formatted: str = pydantic.Field()
    """
    Human-readable label
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
