# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_available_value import BulkAvailableValue


class BulkPropertyEntry(UniversalBaseModel):
    """
    Per-property entry inside the `data.properties` map returned by
    `GET /api/cameras/{id}/properties/all`. Note that this schema is NOT
    the same as `PropertyData`:

    - Field names are prefixed with `current_` (`current_value`,
      `current_hex_value`, `current_formatted`)
    - `writable` is a real JSON boolean, not a stringified one
    - Each entry in `available_values` includes BOTH a numeric `value`
      and a `hex_value` string

    This is because the bulk handler serializes property data inline rather
    than going through the string-string `data` map.
    """

    current_value: float = pydantic.Field()
    """
    Numeric SDK value. Typed as `number` (rather than `int64`) because
    some properties (e.g. `exposure-compensation`, `image-id-num`) emit
    UInt64-range values on the wire that don't fit in a signed 64-bit
    integer. Treat this field as opaque — use `current_hex_value` in
    SET requests.
    """

    current_hex_value: str
    current_formatted: str
    writable: bool
    available_values: typing.List[BulkAvailableValue]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
