# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_property_entry import BulkPropertyEntry


class BulkPropertiesData(UniversalBaseModel):
    """
    Wrapper object inside the bulk-GET `data` field. The
    `properties` member is a map of property name → entry.
    """

    properties: typing.Dict[str, BulkPropertyEntry] = pydantic.Field()
    """
    Map of property name (matches `PropertyName`) to its current value entry
    """

    total_properties: int = pydantic.Field()
    """
    Total number of property entries the camera reported (BEFORE deduplication).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
