# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BulkAvailableValue(UniversalBaseModel):
    value: float = pydantic.Field()
    """
    Numeric SDK value. Typed as `number` (rather than `int64`) because
    some properties emit UInt64-range values on the wire that don't fit
    in a signed 64-bit integer. Treat this field as opaque — use
    `hex_value` in SET requests.
    """

    hex_value: str
    formatted: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
