# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .camera_info_connection_type import CameraInfoConnectionType


class CameraInfo(UniversalBaseModel):
    """
    Camera discovered during enumeration
    """

    id: str
    model: str
    connection_type: typing_extensions.Annotated[
        CameraInfoConnectionType, FieldMetadata(alias="connectionType"), pydantic.Field(alias="connectionType")
    ]
    connected: bool

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
