# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .camera_summary import CameraSummary


class CameraResponse(UniversalBaseModel):
    """
    Generic envelope returned by most camera operations. The shape of
    `data` varies per endpoint — most operations return an empty or
    null `data`; operations that return structured data document a
    specific shape. SDK-generated types can treat `data` as an opaque
    map for generic endpoints.
    """

    success: bool
    message: typing.Optional[str] = None
    camera: typing.Optional[CameraSummary] = None
    data: typing.Optional[typing.Dict[str, typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
