# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .camera_summary import CameraSummary
from .connection_status_response_data import ConnectionStatusResponseData


class ConnectionStatusResponse(UniversalBaseModel):
    """
    Response envelope for `GET /api/cameras/{id}/connection`. When the
    camera is connected, `data.mode` reports the active SDK connection
    mode (`remote` / `remote-transfer` / `contents`) so clients don't
    have to remember what they passed at connect time. When the camera
    is not connected, `data` is omitted.
    """

    success: bool
    message: typing.Optional[str] = None
    camera: typing.Optional[CameraSummary] = None
    data: typing.Optional[ConnectionStatusResponseData] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
