# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_properties_data import BulkPropertiesData
from .camera_summary import CameraSummary


class GetAllPropertiesResponse(UniversalBaseModel):
    success: bool
    message: typing.Optional[str] = None
    camera: typing.Optional[CameraSummary] = None
    data: BulkPropertiesData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
