# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .log_entry_level import LogEntryLevel


class LogEntry(UniversalBaseModel):
    timestamp: typing.Optional[dt.datetime] = None
    level: typing.Optional[LogEntryLevel] = None
    message: typing.Optional[str] = None
    camera_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="cameraId"),
        pydantic.Field(alias="cameraId", description="Camera ID if log is camera-specific"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
