# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class OsdStatus(UniversalBaseModel):
    """
    Wire-format note: `supported` and `enabled` are sent as the literal
    strings `"true"` / `"false"` (the server response envelope serializes
    `data` as a `string→string` map). Clients must coerce to boolean.
    """

    supported: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the connected camera body supports OSD composite frames. Sent as `"true"` / `"false"` — coerce on the client.
    """

    enabled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether OSD mode is currently enabled. Sent as `"true"` / `"false"` — coerce on the client.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
