# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .available_value import AvailableValue


class PropertyData(UniversalBaseModel):
    """
    Single-property GET payload returned under `data` by
    `GET /api/cameras/{id}/properties/{name}`.

    ## Wire-format note for SDK implementers

    The server's response envelope packs `data` as a flat `string→string`
    map, so `writable` arrives as the literal string `"true"` / `"false"`
    rather than a JSON boolean. Fern-generated clients should coerce it
    to a real `boolean` before handing it to consumers. The bulk endpoint
    (`getAllProperties`) already returns a real boolean — see
    `BulkPropertyEntry`.
    """

    property: str = pydantic.Field()
    """
    REST property name (matches `PropertyName` enum)
    """

    value: str = pydantic.Field()
    """
    Hex-encoded current value (use this in SET requests)
    """

    formatted: str = pydantic.Field()
    """
    Human-readable display value (also accepted by SET)
    """

    writable: bool = pydantic.Field()
    """
    Whether this property is currently writable.
    """

    available_values: typing.Optional[typing.List[AvailableValue]] = pydantic.Field(default=None)
    """
    Values the camera currently accepts. Empty array for properties
    with no enumerated values (range properties, freeform strings).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
