# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class SaveInfoData(UniversalBaseModel):
    """
    Wire-format note: `startNo` is sent as a decimal string (the GET
    response packs `data` as a `string→string` map). Clients must coerce
    to integer. `SaveInfoRequest` accepts a real integer on SET.
    """

    path: typing.Optional[str] = None
    prefix: typing.Optional[str] = None
    start_no: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="startNo"),
        pydantic.Field(
            alias="startNo",
            description="Starting file number. Sent as a decimal string on the wire — coerce on the client.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
