# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SdCardFile(UniversalBaseModel):
    content_id: int = pydantic.Field()
    """
    SDK content handle for use in download requests
    """

    file_id: int = pydantic.Field()
    """
    SDK file handle. Always `0` in contents-transfer mode (one file per content).
    Multi-file content (e.g. RAW+JPEG pair) returns separate entries with the
    same `content_id` and distinct `file_id` values.
    """

    file_path: str
    file_size: int = pydantic.Field()
    """
    File size in bytes
    """

    width: typing.Optional[int] = pydantic.Field(default=None)
    """
    Image width in pixels (contents-transfer mode only)
    """

    height: typing.Optional[int] = pydantic.Field(default=None)
    """
    Image height in pixels (contents-transfer mode only)
    """

    creation_year: typing.Optional[int] = None
    creation_month: typing.Optional[int] = None
    creation_day: typing.Optional[int] = None
    creation_hour: typing.Optional[int] = None
    creation_minute: typing.Optional[int] = None
    creation_second: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
