# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SdCardDownloadRequest(UniversalBaseModel):
    """
    Optional save path override. If omitted, uses the connection-time `SetSaveInfo` path.
    """

    save_path: typing.Optional[str] = pydantic.Field(default=None)
    """
    Directory path on host PC to save the file
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
