# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .log_entry import LogEntry


class ServerLogsResponse(UniversalBaseModel):
    success: bool
    logs: typing.List[LogEntry]
    total: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total buffered log count
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
