# This file was auto-generated by Fern from our API Definition.

import typing

ServerStatusServerPlatform = typing.Union[
    typing.Literal["darwin-arm64", "darwin-x64", "linux-arm64", "linux-arm", "linux-x64", "win32-x64", "unknown"],
    typing.Any,
]
