# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .server_status_cameras import ServerStatusCameras
from .server_status_server import ServerStatusServer


class ServerStatus(UniversalBaseModel):
    success: bool
    server: ServerStatusServer
    cameras: ServerStatusCameras

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
