# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .server_status_server_platform import ServerStatusServerPlatform


class ServerStatusServer(UniversalBaseModel):
    version: str = pydantic.Field()
    """
    Server binary version (hardcoded in `handleApiServerStatus`).
    Distinct from the OpenAPI spec version in `info.version`.
    """

    sdk_version: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="sdkVersion"),
        pydantic.Field(alias="sdkVersion", description="Sony Camera Remote SDK version embedded at build time"),
    ]
    uptime: int = pydantic.Field()
    """
    Server uptime in seconds
    """

    platform: ServerStatusServerPlatform = pydantic.Field()
    """
    Host OS platform identifier
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
