# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ZoomSignedSpeedRequest(UniversalBaseModel):
    """
    Signed speed in range `-10..+10`. Positive = zoom in, negative =
    zoom out, magnitude = speed. `0` stops an in-progress zoom.
    """

    speed: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
