# This file was auto-generated by Fern from our API Definition.

import typing

from .zoom_directional_request import ZoomDirectionalRequest
from .zoom_signed_speed_request import ZoomSignedSpeedRequest

ZoomRequest = typing.Union[ZoomDirectionalRequest, ZoomSignedSpeedRequest]
